pycares/errno.py,sha256=XgBmgCKLKV-5EAZIjxxJpORNZiwkyzma5VTKpzPHBms,1039
pycares/utils.py,sha256=WXvoHfPeL7EoKdelvJ9LzIviMH3ijElLxH2Hgz5-0qU,1343
pycares/_version.py,sha256=_gRv4FMmGMjr5UJP_mXgfIWN20vtum0GtYFfalFV1u0,23
pycares/__init__.py,sha256=OslKRMeAcfH3txeLvK4yk1MP6uAkwkh0xV9pHqKrGVw,29754
pycares/_cares.cpython-36m-i386-linux-gnu.so,sha256=4Ta8c39qJ1lunBWhWMlV5femgq7m4Br-VAAULX6LSAI,726148
pycares/__main__.py,sha256=zagpuBSUv3MqoMvzby_5xzSW9ky76DAxWM8b5SMiJrw,2796
pycares-4.2.1.dist-info/top_level.txt,sha256=nIeo7L2XUVBQZO2YE6pH7tlKaBWTfmmRcXbqe_NWYCw,15
pycares-4.2.1.dist-info/WHEEL,sha256=ZCAZ_-NuMW-dDhZkQ7qqC1xHJ3ca2VmGwBHr6Ax-jBo,213
pycares-4.2.1.dist-info/LICENSE,sha256=QnuzpTcgJKJuLCkLJDglErzHyhI0McTdF43WE77qfu4,1070
pycares-4.2.1.dist-info/METADATA,sha256=AVtTbUScWEwlbMhYF8wyhGxKmCLLTZ--oHtnYutACjc,4139
pycares-4.2.1.dist-info/RECORD,,
